service: Datadog-Metric

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment ID}

functions:
  DataDogMetric:
    runtime: nodejs8.3
    handler: handler.main
    memory: 128
    timeout: 30
    access: public
    cron:  
     active: true
     value: '/1 * * * *'
    environmentVariables:
      datadogAPI: Your Data Dog API Token
      spotToken: Your Spotinst Token
      spotAccount: Your Spotinst Account ID

plugins:
  - serverless-spotinst-functions
