service: EMR-Set-Target

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment ID}

functions:
  EMRSetTarget:
    runtime: nodejs8.3
    handler: index.main
    memory: 128
    timeout: 30
    access: private
    environmentVariables:
      spotAccount: Spotinst Account ID
      spotToken: Spotinst API Token
      spotGroup: EMR Elastigroup ID
      max: Max number of capacity units
      min: Min number of capacity units
      target: Target number of capacity units

plugins:
  - serverless-spotinst-functions
