# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: ChatBot

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment ID}

functions:
  SlackBot:
    runtime: nodejs8.3
    handler: handler.main
    memory: 128
    timeout: 30
    access: public
    cron:
      active: true
      value: '0 7 * * 1'

# extend the framework using plugins listed here:
# https://github.com/serverless/plugins
plugins:
  - serverless-spotinst-functions
