service: TwitterBot

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment Variable}

functions:
  TwitterBot:
    runtime: nodejs8.3
    handler: TwitterBot.main
    memory: 128
    timeout: 120
    access: public
    cron:  
     active: true
     value: '/1 * * * *'
    environmentVariables: {
      consumerKey: "Twitter Consumer Key",
      consumerSecret: "Twitter Consumer Secret",
      accessKey: "Twitter Access Key",
      accessSecret: "Twitter Access Secret",
    }

  PictureRecognition:
    runtime: nodejs8.3
    handler: PictureRecognition.main
    memory: 128
    timeout: 60
    access: public
    environmentVariables: {
      visionKey: "Google Vision API Key",
      spotAccount: "Spotinst Account ID",
      spotToken: "Spotinst API Token",
      spotEnvironment: "Spotinst Environment ID"
    }

  FrontEnd:
    runtime: nodejs8.3
    handler: FrontEnd.main
    memory: 128
    timeout: 60
    access: public
    environmentVariables: {
      spotAccount: "Spotinst Account ID",
      spotToken: "Spotinst API Token",
      spotEnvironment: "Spotinst Environment ID"
    }

plugins:
  - serverless-spotinst-functions
