service: Raffle-App

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment ID}

functions:
  HomePage:
    runtime: nodejs8.3
    handler: homePage.main
    memory: 128
    timeout: 30
    access: public

  MySQLConnect:
    runtime: nodejs8.3
    handler: mysqlConnect.main
    memory: 128
    timeout: 30
    access: public

  RunGame:
    runtime: nodejs8.3
    handler: runGame.main
    memory: 128
    timeout: 30
    access: public

  Reset:
    runtime: nodejs8.3
    handler: reset.main
    memory: 128
    timeout: 30
    access: public

  Admin:
    runtime: nodejs8.3
    handler: admin.main
    memory: 128
    timeout: 30
    access: public


plugins:
  - serverless-spotinst-functions
