service: MySQL-Connect

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment ID}

functions:
  SQLConnect:
    runtime: nodejs8.3
    handler: handler.main
    memory: 128
    timeout: 300
    access: public

# extend the framework using plugins listed here:
# https://github.com/serverless/plugins
plugins:
  - serverless-spotinst-functions
