# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: ChatBot

provider:
  name: spotinst
  spotinst:
    environment: {Environment Variables}

functions:
  BasicChatBot:
    runtime: nodejs8.3
    handler: handler.main
    memory: 128
    timeout: 30
    access: public

# extend the framework using plugins listed here:
# https://github.com/serverless/plugins
plugins:
  - serverless-spotinst-functions
