service: Chat-Bot

provider:
  name: spotinst
  spotinst:
    environment: {Environment Variables}

functions:
  ChatBot:
    runtime: nodejs8.3
    handler: handler.main
    memory: 128
    timeout: 30
    access: public

plugins:
  - serverless-spotinst-functions
