service: AWS-Batch-Connect

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment ID} 

functions:
  CheckBatch:
    runtime: python2.7
    handler: handler.main
    memory: 128
    timeout: 30
    access: private

plugins:
  - serverless-spotinst-functions
