service: DeleteAlias

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment}

functions:
  DeleteAlias:
    runtime: nodejs8.3
    handler: handler.main
    memory: 128
    timeout: 30
    access: private
    environmentVariables: {
      spotAccount: "Spotinst Account ID",
      spotToken: "Spotinst API Token",
      spotEnvironment: "Spotinst Environment ID",
      spotAlias: "Alias ID to Delete"
    }

plugins:
  - serverless-spotinst-functions
