# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: sql-python

provider:
  name: spotinst
  spotinst:
    environment: {Your Environement ID}  

functions:
  SQLConnect:
    runtime: python2.7
    handler: handler.main
    memory: 128
    timeout: 30
    access: public
#    cron:
#      active: true
#      value: '*/1 * * * *'

# extend the framework using plugins listed here:
# https://github.com/serverless/plugins
plugins:
  - serverless-spotinst-functions
