service: MySQL-Connect

provider:
  name: spotinst
  spotinst:
    environment: {Your Environement ID}  

functions:
  SQLConnect:
    runtime: python2.7
    handler: handler.main
    memory: 128
    timeout: 30
    access: public

plugins:
  - serverless-spotinst-functions
