service: DataDogEvent

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment ID}

functions:
  DataDogEvent:
    runtime: nodejs8.3
    handler: handler.main
    memory: 128
    timeout: 30
    access: public
    environmentVariables: {
      datadogAPI: "Your Data Dog API Token"
    }

plugins:
  - serverless-spotinst-functions
