
service: DataDog

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment ID}

functions:
  DataDogEvent:
    runtime: nodejs8.3
    handler: handler.main
    memory: 128
    timeout: 30
    access: public

plugins:
  - serverless-spotinst-functions
