
service: DataDog

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment ID}

functions:
  Trigger:
    runtime: nodejs8.3
    handler: trigger.main
    memory: 128
    timeout: 30
    access: public

  Timer:
    runtime: nodejs8.3
    handler: timer.main
    memory: 128
    timeout: 30
    access: public
    cron:  
     active: true
     value: '/1 * * * *'

plugins:
  - serverless-spotinst-functions
