service: PagerDuty-Connect

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment ID} 

functions:
  PagerDutyConnect:
    runtime: nodejs8.3
    handler: handler.main
    memory: 128
    timeout: 30
    access: public
    environmentVariables: {
      pagerToken: "Spotinst Account ID",
      pagerKey: "Spotinst API Token"
    }

plugins:
  - serverless-spotinst-functions
