service: Java8ScaleUpGroup

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment}

functions:
  Java8ScaleUpGroup:
    runtime: java8
    handler: com.serverless.Handler
    memory: 128
    timeout: 30
    access: private
    environmentVariables:
      spotAccount: Spotinst Account ID
      spotToken: Spotinst API Token
      spotGroup: Spotinst Elastigroup ID

plugins:
  - serverless-spotinst-functions
