# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: SpotAlexa

provider:
  name: spotinst
  spotinst:
    environment: env-b91dc981 # NOTE: Remember to add the environment ID

functions:
  AlexaSkill:
    runtime: nodejs8.3
    handler: handler.main
    memory: 128
    timeout: 30
    access: public
#     cron:  # Setup scheduled trigger with cron expression
#      active: true
#      value: '* * * * *'
#    environmentVariables: {
#      Key: "Value",
#    }

# extend the framework using plugins listed here:
# https://github.com/serverless/plugins
plugins:
  - serverless-spotinst-functions
