service: Alexa-Skill

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment Variable} 

functions:
  AlexaSkill:
    runtime: nodejs8.3
    handler: handler.main
    memory: 128
    timeout: 30
    access: public

plugins:
  - serverless-spotinst-functions
