service: ElastigroupAutoScaling

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment Variable}

functions:
  ScaleUp:
    runtime: nodejs8.3
    handler: scaleUp.main
    memory: 128
    timeout: 30
    access: private
#     cron:  # Setup scheduled trigger with cron expression
#      active: true
#      value: '* * * * *'


  ScaleDown:
    runtime: nodejs8.3
    handler: scaleDown.main
    memory: 128
    timeout: 30
    access: private
#     cron:  # Setup scheduled trigger with cron expression
#      active: true
#      value: '* * * * *'


plugins:
  - serverless-spotinst-functions
