service: Get-Elastigroups

provider:
  name: spotinst
  spotinst:
    environment: {Your Environment ID}

functions:
  GetElastigroups:
    runtime: python2.7
    handler: handler.main
    memory: 128
    timeout: 30

plugins:
  - serverless-spotinst-functions
